### PR TITLE
Fix sum-where with Int columns

### LINKED ISSUE #156: `Sum If` cannot be applied to `Int` Columns
### Describe the bug

applying `Sum If` expression in Metabase to `Int` columns will generate invalid SQL

#### Given Schema 
```sql
create table public.sum_if_test
(
    id            Int64,
    int_value     Int64,
    discriminator String
) ENGINE = MergeTree()
      primary key (id, discriminator);
```

#### Given Test Data

```sql
insert into public.sum_if_test values (1, 1, 'foo');
insert into public.sum_if_test values (2, 1, 'foo');
insert into public.sum_if_test values (3, 3, 'bar');
insert into public.sum_if_test values (4, 5, 'bar');
```

#### Given Metbase Report Configuration

custom expression configured in Metabase when summarizing this table:

image

Will generate SQL:

```sql
SELECT sum(CASE WHEN `public`.`sum_if_test`.`discriminator` = 'bar' THEN `public`.`sum_if_test`.`int_value` ELSE 0.0 END) AS `sum_if_with_int`
FROM `public`.`sum_if_test`
```

using a float `0.0` default value instead of `0` in `ELSE 0.0`

### Expected behaviour

`Sum If` expression can be applied to `Int` typed columns

### Error log

```
ode: 386. DB::Exception: There is no supertype for types Float64, Int64 because some of them are integers and some are floating point, but there is no floating point type, that can exactly represent all required integers: While processing if(discriminator = 'bar', int_value, 0.). (NO_COMMON_TYPE) (version 22.8.15.1) , server ClickHouseNode [uri=https://(...)/public, options={use_server_time_zone_for_dates=true,use_no_proxy=false,product_name=metabase/1.1.2}]@92216918
```

#### Environment
* metabase-clickhouse-driver version: 1.1.2
* Metabase version: v0.46.2
* OS: Linux

#### ClickHouse server
* ClickHouse Server version: 22.8.15

### PR DESCRIPTION
**Pull request by slvrtrn**
## Summary
* Resolves #156 
* Bump ClickHouse to 23.4
* Bump Metabase to 0.46.2

## Checklist
- [x] Unit and integration tests covering the common scenarios were added
- [x] A human-readable description of the changes was provided to include in CHANGELOG

### CODE REVIEW

**Review by mshustov — APPROVED** [review]

File: src/metabase/driver/clickhouse.clj [hunk 1]
```diff
@@ -467,13 +467,18 @@
...
+  (hsql/call :case (hsql/call :> (hsql/call :count) 0)
              (hsql/call :sum
-                        (hsql/call :case (sql.qp/->honeysql driver pred) 1.0 :else 0.0))
+                        (hsql/call :case (sql.qp/->honeysql driver pred) 1
+                                   :else 0))
              :else nil))
 
+(defmethod sql.qp/->honeysql [:clickhouse :sum-where]
+  [driver [_ field pred]]
+  (hsql/call :sum (hsql/call
```
Comment (lucas-tubi) [inline src/metabase/driver/clickhouse.clj:478]: why cannot it use `sumIf` directly?
